server {
    listen 80;
    server_name _;

    root /usr/share/nginx/html;
    index index.html;

    # React Router ke liye - har route pe index.html serve karo
    location / {
        try_files $uri $uri/ /index.html;
    }
}
